
language: objective-c
osx_image: xcode7.3

script:
  - xctool -project Canvas.xcodeproj -scheme 'Canvas' -configuration Debug -sdk iphonesimulator -arch i386 test
  - xctool -project Canvas.xcodeproj -scheme 'Canvas' -configuration Debug test
